// Utility to generate high-quality 3D geometries and pack them as Binary STL files
// The binary STL format consists of:
// - 80-byte header
// - 4-byte little-endian uint32 (number of triangles)
// - For each triangle:
//   - Normal vector: 3x 32-bit floats (12 bytes)
//   - Vertex 1: 3x 32-bit floats (12 bytes)
//   - Vertex 2: 3x 32-bit floats (12 bytes)
//   - Vertex 3: 3x 32-bit floats (12 bytes)
//   - Attribute byte count: 2 bytes (usually 0)
// Total size = 80 + 4 + (n * 50) bytes

import * as THREE from 'three';

interface Vertex {
  x: number;
  y: number;
  z: number;
}

interface Triangle {
  normal: [number, number, number];
  v1: [number, number, number];
  v2: [number, number, number];
  v3: [number, number, number];
  color?: [number, number, number]; // RGB 0-255 (STL binario con color por cara)
}

// Simple cross product helper to calculate outward normals
function calculateNormal(v1: [number, number, number], v2: [number, number, number], v3: [number, number, number]): [number, number, number] {
  const ux = v2[0] - v1[0];
  const uy = v2[1] - v1[1];
  const uz = v2[2] - v1[2];
  
  const vx = v3[0] - v1[0];
  const vy = v3[1] - v1[1];
  const vz = v3[2] - v1[2];
  
  const nx = uy * vz - uz * vy;
  const ny = uz * vx - ux * vz;
  const nz = ux * vy - uy * vx;
  
  const len = Math.sqrt(nx * nx + ny * ny + nz * nz);
  if (len === 0) return [0, 0, 1];
  return [nx / len, ny / len, nz / len];
}

// Core function to convert an array of triangles into a binary STL ArrayBuffer
export function serializeBinarySTL(triangles: Triangle[], filename: string = "Procedural"): ArrayBuffer {
  const hasColor = triangles.some(t => t.color);
  const headerText = `STL generated by STL 3D Viewer - ${filename.substring(0, 40)}`;
  const buffer = new ArrayBuffer(84 + triangles.length * 50);
  const view = new DataView(buffer);
  
  // Write header (80 bytes). Con color: "COLOR=" + RGBA por defecto, como lee STLLoader de three.js
  const textStart = hasColor ? 10 : 0;
  for (let i = 0; i < 80; i++) {
    const ch = i - textStart;
    if (ch >= 0 && ch < headerText.length) {
      view.setUint8(i, headerText.charCodeAt(ch));
    } else {
      view.setUint8(i, 32); // Space character
    }
  }
  if (hasColor) {
    'COLOR='.split('').forEach((c, i) => view.setUint8(i, c.charCodeAt(0)));
    view.setUint8(6, 200); view.setUint8(7, 200); view.setUint8(8, 200); view.setUint8(9, 255);
  }
  
  // Write triangle count (4 bytes, little endian)
  view.setUint32(80, triangles.length, true);
  
  let offset = 84;
  for (const t of triangles) {
    // Write Normal (3x floats)
    view.setFloat32(offset + 0, t.normal[0], true);
    view.setFloat32(offset + 4, t.normal[1], true);
    view.setFloat32(offset + 8, t.normal[2], true);
    
    // Write V1 (3x floats)
    view.setFloat32(offset + 12, t.v1[0], true);
    view.setFloat32(offset + 16, t.v1[1], true);
    view.setFloat32(offset + 20, t.v1[2], true);
    
    // Write V2 (3x floats)
    view.setFloat32(offset + 24, t.v2[0], true);
    view.setFloat32(offset + 28, t.v2[1], true);
    view.setFloat32(offset + 32, t.v2[2], true);
    
    // Write V3 (3x floats)
    view.setFloat32(offset + 36, t.v3[0], true);
    view.setFloat32(offset + 40, t.v3[1], true);
    view.setFloat32(offset + 44, t.v3[2], true);
    
    // Attribute byte count (2 bytes): con color, 15 bits RGB (bit 15 = 0: color propio; 1: el de la cabecera)
    if (hasColor) {
      const c = t.color;
      const packed = c
        ? ((c[0] >> 3) & 0x1f) | (((c[1] >> 3) & 0x1f) << 5) | (((c[2] >> 3) & 0x1f) << 10)
        : 0x8000;
      view.setUint16(offset + 48, packed, true);
    } else {
      view.setUint16(offset + 48, 0, true);
    }
    
    offset += 50;
  }
  
  return buffer;
}

// 1. CALIBRATION CUBE (Cubo de Calibración de 20x20x20 mm)
export function generateCalibrationCube(): ArrayBuffer {
  const size = 20; // 20mm
  const half = size / 2;
  
  const vertices: Vertex[] = [
    { x: -half, y: -half, z: -half }, // 0
    { x:  half, y: -half, z: -half }, // 1
    { x:  half, y:  half, z: -half }, // 2
    { x: -half, y:  half, z: -half }, // 3
    { x: -half, y: -half, z:  half }, // 4
    { x:  half, y: -half, z:  half }, // 5
    { x:  half, y:  half, z:  half }, // 6
    { x: -half, y:  half, z:  half }, // 7
  ];
  
  // Define faces: each face has 2 triangles. Normals point outwards.
  const facesDef = [
    // Bottom (-Z)
    [2, 1, 0], [3, 2, 0],
    // Top (+Z)
    [4, 5, 6], [4, 6, 7],
    // Front (-Y)
    [0, 1, 5], [0, 5, 4],
    // Back (+Y)
    [2, 3, 7], [2, 7, 6],
    // Left (-X)
    [3, 0, 4], [3, 4, 7],
    // Right (+X)
    [1, 2, 6], [1, 6, 5]
  ];
  
  const triangles: Triangle[] = [];
  for (const f of facesDef) {
    const v1 = vertices[f[0]];
    const v2 = vertices[f[1]];
    const v3 = vertices[f[2]];
    
    const p1: [number, number, number] = [v1.x, v1.y, v1.z];
    const p2: [number, number, number] = [v2.x, v2.y, v2.z];
    const p3: [number, number, number] = [v3.x, v3.y, v3.z];
    const normal = calculateNormal(p1, p2, p3);
    
    triangles.push({ normal, v1: p1, v2: p2, v3: p3 });
  }
  
  return serializeBinarySTL(triangles, "CalibrationCube_20mm");
}

// 2. FACETED DIAMOND (Gema Brillante de 25mm)
export function generateFacetedDiamond(): ArrayBuffer {
  const rTop = 12.0;       // top radius ring
  const rGirdle = 15.0;    // girdle (widest point)
  const hTop = 5.0;        // height girdle to table (top)
  const hPaved = 15.0;     // height girdle to bottom culet
  
  // We can build top center table (0, 0, hTop)
  // Crown rings: top ring (8 vertices), girdle ring (8 vertices), bottom culet (0, 0, -hPaved)
  const segments = 8;
  const vertices: Vertex[] = [];
  
  const tableZ = hTop;
  const girdleZ = 0;
  const culetZ = -hPaved;
  
  // Table center (Vertex 0)
  vertices.push({ x: 0, y: 0, z: tableZ });
  
  // Upper ring (8 points) (Vertices 1..8)
  for (let i = 0; i < segments; i++) {
    const ang = (i / segments) * Math.PI * 2;
    vertices.push({
      x: Math.cos(ang) * rTop,
      y: Math.sin(ang) * rTop,
      z: tableZ
    });
  }
  
  // Girdle ring (8 points) (Vertices 9..16)
  for (let i = 0; i < segments; i++) {
    const ang = ((i + 0.5) / segments) * Math.PI * 2; // offset to break alignment and create facets
    vertices.push({
      x: Math.cos(ang) * rGirdle,
      y: Math.sin(ang) * rGirdle,
      z: girdleZ
    });
  }
  
  // Culet (bottom point) (Vertex 17)
  vertices.push({ x: 0, y: 0, z: culetZ });
  
  const triangles: Triangle[] = [];
  
  // Crown Top Table (Polygon fans around vertex 0)
  for (let i = 0; i < segments; i++) {
    const next = (i + 1) % segments;
    const v1 = 0;
    const v2 = 1 + i;
    const v3 = 1 + next;
    
    const p1: [number, number, number] = [vertices[v1].x, vertices[v1].y, vertices[v1].z];
    const p2: [number, number, number] = [vertices[v3].x, vertices[v3].y, vertices[v3].z]; // Swapped for normal
    const p3: [number, number, number] = [vertices[v2].x, vertices[v2].y, vertices[v2].z];
    
    triangles.push({ normal: calculateNormal(p1, p2, p3), v1: p1, v2: p2, v3: p3 });
  }
  
  // Crown Upper Triangles (Table ring to Girdle)
  for (let i = 0; i < segments; i++) {
    const next = (i + 1) % segments;
    const u1 = 1 + i;
    const u2 = 1 + next;
    const g1 = 9 + i;
    const g2 = 9 + ((i - 1 + segments) % segments);
    
    // Triangle pointing up (u1, u2, g1)
    {
      const p1: [number, number, number] = [vertices[u1].x, vertices[u1].y, vertices[u1].z];
      const p2: [number, number, number] = [vertices[u2].x, vertices[u2].y, vertices[u2].z];
      const p3: [number, number, number] = [vertices[g1].x, vertices[g1].y, vertices[g1].z];
      triangles.push({ normal: calculateNormal(p1, p2, p3), v1: p1, v2: p2, v3: p3 });
    }
    
    // Triangle pointing down (u1, g1, g2)
    {
      const p1: [number, number, number] = [vertices[u1].x, vertices[u1].y, vertices[u1].z];
      const p2: [number, number, number] = [vertices[g1].x, vertices[g1].y, vertices[g1].z];
      const p3: [number, number, number] = [vertices[g2].x, vertices[g2].y, vertices[g2].z];
      triangles.push({ normal: calculateNormal(p1, p2, p3), v1: p1, v2: p2, v3: p3 });
    }
  }
  
  // Pavilion (Girdle to Culet)
  const culetIdx = 17;
  for (let i = 0; i < segments; i++) {
    const next = (i + 1) % segments;
    const g1 = 9 + i;
    const g2 = 9 + next;
    
    const p1: [number, number, number] = [vertices[g2].x, vertices[g2].y, vertices[g2].z]; // Swapped for outward normals
    const p2: [number, number, number] = [vertices[g1].x, vertices[g1].y, vertices[g1].z];
    const p3: [number, number, number] = [vertices[culetIdx].x, vertices[culetIdx].y, vertices[culetIdx].z];
    
    triangles.push({ normal: calculateNormal(p1, p2, p3), v1: p1, v2: p2, v3: p3 });
  }
  
  return serializeBinarySTL(triangles, "FacetedDiamond_25mm");
}

// 3. RUEDA GIRATORIA CON RODAMIENTO DE BOLAS (conjunto completo)
// Medidas (mm) del plano acotado; mismas que la macro de SolidWorks.
// Ejes del conjunto: Y arriba, X = sentido de rodadura, Z = eje de la rueda,
// cara superior exterior de la horquilla en Y = 0, giro en X = 0.

// Convierte una geometría de three en triángulos STL (con la matriz dada).
// Orienta cada sólido hacia fuera según su volumen con signo y descarta triángulos degenerados.
function geoToTriangles(src: THREE.BufferGeometry, m: THREE.Matrix4, color?: [number, number, number]): Triangle[] {
  const g = src.index ? src.toNonIndexed() : src.clone();
  g.applyMatrix4(m);
  const pos = g.getAttribute('position');
  const a = new THREE.Vector3();
  const b = new THREE.Vector3();
  const c = new THREE.Vector3();
  const cr = new THREE.Vector3();
  let vol = 0;
  for (let i = 0; i < pos.count; i += 3) {
    a.fromBufferAttribute(pos, i);
    b.fromBufferAttribute(pos, i + 1);
    c.fromBufferAttribute(pos, i + 2);
    vol += a.dot(cr.crossVectors(b, c));
  }
  const flip = vol < 0;
  const tris: Triangle[] = [];
  const e1 = new THREE.Vector3();
  const e2 = new THREE.Vector3();
  for (let i = 0; i < pos.count; i += 3) {
    a.fromBufferAttribute(pos, i);
    b.fromBufferAttribute(pos, i + 1);
    c.fromBufferAttribute(pos, i + 2);
    e1.subVectors(b, a);
    e2.subVectors(c, a);
    if (cr.crossVectors(e1, e2).length() < 1e-9) continue;
    const v1: [number, number, number] = [a.x, a.y, a.z];
    let v2: [number, number, number] = [b.x, b.y, b.z];
    let v3: [number, number, number] = [c.x, c.y, c.z];
    if (flip) { const t = v2; v2 = v3; v3 = t; }
    tris.push({ normal: calculateNormal(v1, v2, v3), v1, v2, v3, color });
  }
  g.dispose();
  return tris;
}

// Sólido de revolución sobre el eje Y a partir de un perfil cerrado [radio, y]
function lathe(profile: [number, number][], segments = 72): THREE.BufferGeometry {
  const pts = profile.map(([r, y]) => new THREE.Vector2(r, y));
  pts.push(pts[0].clone());
  return new THREE.LatheGeometry(pts, segments);
}

export function generateRuedaGiratoria(): ArrayBuffer {
  // Horquilla
  const ANCHO_EXT = 45.5, PARED = 4.8, ANCHO_SUP = 39.7, E_PUENTE = 5;
  const R_PUNTA = 15.9, PROF_EJE = 41.3, OFF_EJE = 8.7;
  // Eje, rueda
  const D_EJE = 9.6, L_EJE = 52.4, E_CABEZA = 4.8, D_COLLAR = 16.1, E_COLLAR = 2;
  const D_RUEDA = 57.4, E_BANDA = 4.9, ANCHO_RUEDA = 30.2, E_NERVIO = 6.5, D_CUBO = 23, L_CUBO = 35;
  // Tornillo y tuerca
  const D_VASTAGO = 17.7, L_VASTAGO = 41.9, L_ROSCA = 18.8, D_ROSCA = 12.2;
  const ANCHO_RANURA = 1.8, PROF_RANURA = 2.3;
  const AC_TUERCA = 21.7, H_TUERCA = 12.2, D_BRIDA = 24, E_BRIDA = 1.2;
  const Y_TORN = -7.2, Y_TUERCA = 19;
  // Rodamiento de bolas
  const D_PISTA = 50.1, E_PISTA = 4.6, D_DISCO = 57.9, D_BOLA = 5.8, D_PASO = 41.6, Y_BOLA = 7.67, N_BOLAS = 14;
  const Y_DISCO_TOP = 13.9, R_DISCO_PLANO = 20.3, CAIDA_DISCO = 5.9, E_DISCO = 2.5, R_HUECO_DISCO = 9.5;
  const ZC = ANCHO_EXT / 2;

  const tris: Triangle[] = [];
  // Un color por pieza (RGB 0-255)
  const COLOR: Record<string, [number, number, number]> = {
    horquilla: [59, 130, 246],
    rueda: [239, 68, 68],
    eje: [161, 161, 170],
    tornillo: [250, 204, 21],
    tuerca: [34, 197, 94],
    pista: [139, 92, 246],
    disco: [6, 182, 212],
    bola: [229, 231, 235]
  };
  const add = (g: THREE.BufferGeometry, m: THREE.Matrix4, color: [number, number, number]) => {
    const t = geoToTriangles(g, m, color);
    for (let i = 0; i < t.length; i++) tris.push(t[i]);
    g.dispose();
  };
  const move = (x: number, y: number, z: number) => new THREE.Matrix4().makeTranslation(x, y, z);
  // extrusión (a lo largo de +Z local) -> eje Y del conjunto; revolución (eje Y) -> eje Z del conjunto
  const zToY = (x: number, y: number, z: number) => move(x, y, z).multiply(new THREE.Matrix4().makeRotationX(-Math.PI / 2));
  const yToZ = (x: number, y: number, z: number) => move(x, y, z).multiply(new THREE.Matrix4().makeRotationX(Math.PI / 2));
  const extrude = (shape: THREE.Shape, depth: number) =>
    new THREE.ExtrudeGeometry(shape, { depth, bevelEnabled: false, curveSegments: 48 });
  const circleHole = (cx: number, cy: number, r: number) => {
    const h = new THREE.Path();
    h.absarc(cx, cy, r, 0, Math.PI * 2, false);
    return h;
  };

  // 1. HORQUILLA: puente superior + dos paredes con punta redonda y taladro del eje
  const hs = ANCHO_SUP / 2;
  const puente = new THREE.Shape();
  puente.moveTo(-hs, 0); puente.lineTo(hs, 0); puente.lineTo(hs, -ANCHO_EXT); puente.lineTo(-hs, -ANCHO_EXT);
  puente.holes.push(circleHole(0, -ZC, D_VASTAGO / 2));
  add(extrude(puente, E_PUENTE), zToY(0, -E_PUENTE, 0), COLOR.horquilla);

  const pared = () => {
    const cx = OFF_EJE, cy = -PROF_EJE;
    const s = new THREE.Shape();
    s.moveTo(-hs, 0); s.lineTo(hs, 0); s.lineTo(cx + R_PUNTA, cy);
    s.absarc(cx, cy, R_PUNTA, 0, -Math.PI, true);
    s.lineTo(-hs, 0);
    s.holes.push(circleHole(cx, cy, D_EJE / 2));
    return s;
  };
  add(extrude(pared(), PARED), move(0, 0, 0), COLOR.horquilla);
  add(extrude(pared(), PARED), move(0, 0, ANCHO_EXT - PARED), COLOR.horquilla);

  // 2. RUEDA (eje Z): cubo, nervio central y banda, en un solo perfil de revolución
  const rBanda = D_RUEDA / 2, rInt = (D_RUEDA - 2 * E_BANDA) / 2, rCubo = D_CUBO / 2;
  const z0 = (L_CUBO - ANCHO_RUEDA) / 2, zN0 = (L_CUBO - E_NERVIO) / 2, zN1 = zN0 + E_NERVIO;
  add(lathe([
    [D_EJE / 2, 0], [rCubo, 0], [rCubo, zN0], [rInt, zN0], [rInt, z0], [rBanda, z0],
    [rBanda, z0 + ANCHO_RUEDA], [rInt, z0 + ANCHO_RUEDA], [rInt, zN1], [rCubo, zN1],
    [rCubo, L_CUBO], [D_EJE / 2, L_CUBO]
  ]), yToZ(OFF_EJE, -PROF_EJE, (ANCHO_EXT - L_CUBO) / 2), COLOR.rueda);

  // 3. EJE de la rueda con collar en el extremo derecho
  add(lathe([
    [0, 0], [D_EJE / 2, 0], [D_EJE / 2, L_EJE - E_COLLAR], [D_COLLAR / 2, L_EJE - E_COLLAR],
    [D_COLLAR / 2, L_EJE], [0, L_EJE]
  ]), yToZ(OFF_EJE, -PROF_EJE, -E_CABEZA), COLOR.eje);

  // 4. TORNILLO de giro: caña Ø17,7, tramo roscado Ø12,2 y ranura en el extremo
  const rRosca = D_ROSCA / 2, yRanura = L_VASTAGO - PROF_RANURA;
  add(lathe([
    [0, 0], [D_VASTAGO / 2, 0], [D_VASTAGO / 2, L_VASTAGO - L_ROSCA], [rRosca, L_VASTAGO - L_ROSCA],
    [rRosca, yRanura], [0, yRanura]
  ]), move(0, Y_TORN, ZC), COLOR.tornillo);
  const xs = ANCHO_RANURA / 2, gam = Math.acos(-xs / rRosca);
  for (const lado of [-1, 1]) {
    // dos mitades del extremo del vástago, separadas por la ranura (lado -1: x <= -xs; lado 1: x >= xs)
    const mitad = new THREE.Shape();
    const n = 24;
    for (let i = 0; i <= n; i++) {
      const th = gam + ((2 * Math.PI - 2 * gam) * i) / n;
      const x = lado === -1 ? rRosca * Math.cos(th) : -rRosca * Math.cos(th);
      const y = rRosca * Math.sin(th);
      if (i === 0) mitad.moveTo(x, y); else mitad.lineTo(x, y);
    }
    add(extrude(mitad, PROF_RANURA), zToY(0, Y_TORN + yRanura, ZC), COLOR.tornillo);
  }

  // 5. TUERCA hexagonal con brida
  add(lathe([[rRosca, 0], [D_BRIDA / 2, 0], [D_BRIDA / 2, E_BRIDA], [rRosca, E_BRIDA]]), move(0, Y_TUERCA, ZC), COLOR.tuerca);
  const hex = new THREE.Shape();
  for (let k = 0; k < 6; k++) {
    const th = (k * Math.PI) / 3;
    const x = (AC_TUERCA / 2) * Math.cos(th), y = (AC_TUERCA / 2) * Math.sin(th);
    if (k === 0) hex.moveTo(x, y); else hex.lineTo(x, y);
  }
  hex.holes.push(circleHole(0, 0, rRosca));
  add(extrude(hex, H_TUERCA - E_BRIDA), zToY(0, Y_TUERCA + E_BRIDA, ZC), COLOR.tuerca);

  // 6. PISTA INFERIOR del rodamiento
  add(lathe([[D_VASTAGO / 2, 0], [D_PISTA / 2, 0], [D_PISTA / 2, E_PISTA], [D_VASTAGO / 2, E_PISTA]]), move(0, 0, ZC), COLOR.pista);

  // 7. DISCO SUPERIOR en forma de plato
  const rO = D_DISCO / 2, yT = Y_DISCO_TOP;
  add(lathe([
    [R_HUECO_DISCO, yT], [R_DISCO_PLANO, yT], [rO, yT - CAIDA_DISCO], [rO, yT - CAIDA_DISCO - E_DISCO],
    [R_DISCO_PLANO, yT - E_DISCO], [R_HUECO_DISCO, yT - E_DISCO]
  ]), move(0, 0, ZC), COLOR.disco);

  // 8. BOLAS
  const rb = D_PASO / 2;
  for (let i = 0; i < N_BOLAS; i++) {
    const ang = (2 * Math.PI * i) / N_BOLAS;
    add(new THREE.SphereGeometry(D_BOLA / 2, 28, 18), move(rb * Math.cos(ang), Y_BOLA, ZC + rb * Math.sin(ang)), COLOR.bola);
  }

  return serializeBinarySTL(tris, 'RuedaGiratoria');
}
